### ISSUE TITLE
Mobile apps day to-do list

### ISSUE THREAD

**Issue by tianhaoz95** [tianhaoz95/investment-todo-app#2]
**Mobile apps day**

- [ ] Getting started with the design for the to-do app for investors.
- [ ] Finish the docs for the overall design.
- [ ] Finish the repository structure.
- [ ] Finish the data structure definition.

_Originally posted by @tianhaoz95 in https://github.com/tianhaoz95/codeNboba/issues/101#issuecomment-703556171_
